FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /code

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt 
RUN pip install --no-cache-dir gunicorn

COPY . /code/

EXPOSE 8000

CMD ["gunicorn", "drf_app.wsgi:application", "--bind", "0.0.0.0:8000"]
